import { getCurrentSession } from "@/actions/auth/getCurrentSession";
import SessionProvider from "@/components/wrappers/SessionProvider";
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = await getCurrentSession();

  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CookiesProvider>
          <SessionProvider value={session}>


        {children}
          </SessionProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
